# Generated by Django 5.2.7 on 2025-10-24 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('recibido_por', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.equipo')),
            ],
        ),
    ]
