# Generated by Django 5.2.7 on 2025-10-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=50)),
                ('descripcion_falla', models.TextField()),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='En recepción', max_length=50)),
            ],
        ),
    ]
